name: Pipeline Seguro

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    # Injeção segura dos secrets como variáveis de ambiente na memória do job
    env:
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executar aplicacao
        run: python app/main.py